security:
    # Encoders (ou hashers) pour les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Pare-feux de sécurité
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # custom_authenticator: App\Security\AppAuthenticator
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path: /
                # always_remember_me: true

    # Contrôle d'accès
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

services:
    App\Security\EmailVerifier:
        arguments:
            $verifyEmailHelper: '@SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface'
            $mailer: '@mailer'
            $entityManager: '@doctrine.orm.entity_manager'
    App\Security\AppAuthentificator:
        arguments:
            $urlGenerator: '@router'
            $userRepository: '@App\Repository\UserRepository'
            $helper: '@SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface'
            $mailer: '@mailer'
        tags:
            - { name: 'security.authenticator' }

